FORMAT: 1A
HOST: https://api.previo.cz/app/

# API - Alfred app

## Pusher
 ```
 {
   actions: ['RESERVATION', 'SERVICES'],
 }
 ```
 - `action` (the data specification that contains the data object)
  - `reservation` - Changes in reservation API
  - `account` - Changes in account API
  - `services` - Changes in services API - in future
  - `room_key` - Changes in room key API

- `data` - Attached data in json format

## Pusher chanels
 - On login
   - Set chanel `resId = 342412`
 - On logout
   - Remove chanel `resId`

## Deep Links
- `alfred://payment/success` - opens success payment dialog
- `alfred://payment/failure` - opens fail payment dialog
- `https://myalfred.cz/login/{PIN}` - Deeplink in vourcher, for login into My Alfred app
- `https://myalfred.cz/roomKeys?pin={PIN}&invitationCode={INVITATION_CODE}&endpointUId={ENDPOINT_UID}` - Deeplink in confirm email for Assa Abloy locks

`{PIN}` - `7DE3SA` ~ Pin for log in into My Alfred app

`{INVITATION_CODE}` - `GSTD-ZE5W-85DE-0U54` ~ Invitation key for Assa Abloy SDK

`{ENDPOINT_UID}` - `89251b7d-b27b-4416-b7ad-cbf0877257b3` ~ Id of Assa Abloy end-point

## Authentication [/authentication]

### Get access token [GET /authentication/accessToken{?code}]

+ Request (application/json)
    + Headers

            Accept-Language: cs
            X-Previo-App-ID: 3
            User-Agent: iPhoneX - Model name of user device
            X-Device-UUID: 765ce9ec-29f2-423a-9724-6512cef6bf19 
            
+ Parameters
    + code: ABC123 (string,required) - Unique reservation or commission identifier, 6 capital chars and numbers
    
+ Response 200 (application/json)
    + Attributes (Authentication)
    
+ Response 400 (application/json) 
    + Attributes (AuthError)

### Refresh access token [GET /authentication/refreshToken{?refreshToken}]

+ Request (application/json)
    + Headers

            Accept-Language: cs
            X-Previo-App-ID: 3

+ Parameters
    + refreshToken: 7e8HVcDWhnHnQCL8wqvKM95c7e8HVcDW (string,required) - The refresh token.
    
+ Response 200 (application/json)
    
+ Response 400 (application/json) 
    + Attributes (AuthRefreshError)

## Reservation [/reservation]

### Get reservation [GET /reservation]

+ Request (application/json)
    + Headers
    
            Accept-Language: cs
            X-Previo-App-ID: 3
            Authorization: Bearer 7e8HVcDWhnHnQCL8wqvKM95c7e8HVcDW
            X-Device-UUID: 765ce9ec-29f2-423a-9724-6512cef6bf19
            
+ Response 200 (application/json)
    + Attributes (Reservation)
    
+ Response 404 (application/json) 
    + Attributes (Error)
    
+ Response 401 (application/json)
    + Attributes (AuthTimeoutError)

### Cancel reservation [PUT /reservation/cancel]

`In development`

+ Request (application/json)
    + Headers
    
            Accept-Language: cs
            X-Previo-App-ID: 3
            Authorization: Bearer 7e8HVcDWhnHnQCL8wqvKM95c7e8HVcDW
            X-Device-UUID: 765ce9ec-29f2-423a-9724-6512cef6bf19
    
+ Response 200 (application/json)

+ Response 400 (application/json)
    + Attributes (Error)

### Check in [PUT /reservation/checkIn]

+ Request (application/json)
    + Attributes (GuestCheckIn)
    + Headers
    
            Accept-Language: cs
            X-Previo-App-ID: 3
            Authorization: Bearer 7e8HVcDWhnHnQCL8wqvKM95c7e8HVcDW
            X-Device-UUID: 765ce9ec-29f2-423a-9724-6512cef6bf19
        
+ Response 200 (application/json)

+ Response 400 (application/json)
    + Attributes (Error)
    
### Check in guest signature [POST /reservation/checkInSignature]

+ Request (application/json)
    + Attributes (GuestCheckInSignature)
    + Headers
    
            Accept-Language: cs
            X-Previo-App-ID: 3
            Authorization: Bearer 7e8HVcDWhnHnQCL8wqvKM95c7e8HVcDW
            X-Device-UUID: 765ce9ec-29f2-423a-9724-6512cef6bf19
        
+ Response 200 (application/json)

+ Response 400 (application/json)
    + Attributes (Error)

### Check out [PUT /reservation/checkOut]

+ Request (application/json)
    + Headers
    
            Accept-Language: cs
            X-Previo-App-ID: 3
            Authorization: Bearer 7e8HVcDWhnHnQCL8wqvKM95c7e8HVcDW
            X-Device-UUID: 765ce9ec-29f2-423a-9724-6512cef6bf19

+ Response 200 (application/json)

+ Response 400 (application/json)
    + Attributes (Error)
    
+ Response 401 (application/json)
    + Attributes (AuthTimeoutError)
    
### Note [POST /reservation/note]

+ Request (application/json)
    + Attributes (NoteCheckIn)
    + Headers
    
            Accept-Language: cs
            X-Previo-App-ID: 3
            Authorization: Bearer 7e8HVcDWhnHnQCL8wqvKM95c7e8HVcDW
            X-Device-UUID: 765ce9ec-29f2-423a-9724-6512cef6bf19

+ Response 200 (application/json)

+ Response 400 (application/json)
    + Attributes (Error)

### Pay [GET /reservation/pay{?comId}{?groupAccount}]

+ Request (application/json)
    + Headers
    
            Accept-Language: cs
            X-Previo-App-ID: 3
            Authorization: Bearer 7e8HVcDWhnHnQCL8wqvKM95c7e8HVcDW
            X-Device-UUID: 765ce9ec-29f2-423a-9724-6512cef6bf19

+ Parameters
    + comId: 93481 (number, optional) - Unique commission identifier, if we want to pay one room account only
    + groupAccount: true (boolean, optional) - Pay group account only if true

+ Response 200 (application/json)
    + Attributes (PayUrl)
    
+ Response 400 (application/json)
    + Attributes (Error)
    
+ Response 401 (application/json)
    + Attributes (AuthTimeoutError)

### Post review [POST /reservation/review]

+ Request (application/json)
    + Attributes (Review)
    + Headers
    
            Accept-Language: cs
            X-Previo-App-ID: 3
            Authorization: Bearer 7e8HVcDWhnHnQCL8wqvKM95c7e8HVcDW
            X-Device-UUID: 765ce9ec-29f2-423a-9724-6512cef6bf19
            
+ Response 200 (application/json)

+ Response 400 (application/json)
    + Attributes (Error)

+ Response 401 (application/json)
    + Attributes (AuthTimeoutError)

### Get rooms keys [GET /reservation/roomKeys]

+ Request (application/json)
    + Headers
    
            Accept-Language: cs
            X-Previo-App-ID: 3
            Authorization: Bearer 7e8HVcDWhnHnQCL8wqvKM95c7e8HVcDW
            X-Device-UUID: 765ce9ec-29f2-423a-9724-6512cef6bf19
            
+ Response 200 (application/json)
    + Attributes (Keychain)

+ Response 400 (application/json)
    + Attributes (Error)

+ Response 401 (application/json)
    + Attributes (AuthTimeoutError)

### Initialize mobile key [POST /reservation/roomKeysInitialization]

+ Request (application/json)
    + Headers
    
            Accept-Language: cs
            X-Previo-App-ID: 3
            Authorization: Bearer 7e8HVcDWhnHnQCL8wqvKM95c7e8HVcDW
            X-Device-UUID: 765ce9ec-29f2-423a-9724-6512cef6bf19
            
+ Response 200 (application/json)

+ Response 400 (application/json)
    + Attributes (Error)

+ Response 401 (application/json)
    + Attributes (AuthTimeoutError)

### Change confirm email for Assa Abloy locks [PUT /reservation/roomKeysConfirmMail]

+ Request (application/json)
    + Headers

            Accept-Language: cs
            X-Previo-App-ID: 3
            Authorization: Bearer 7e8HVcDWhnHnQCL8wqvKM95c7e8HVcDW
            X-Device-UUID: 765ce9ec-29f2-423a-9724-6512cef6bf19
            
    + Attributes (AssaAbloyEmail)
            
+ Response 200 (application/json)

+ Response 400 (application/json)
    + Attributes (Error)

+ Response 401 (application/json)
    + Attributes (AuthTimeoutError)

### Approved endpoint in Assa Abloy locks [PUT /reservation/roomKeysApproved]

+ Request (application/json)
    + Headers
    
            Accept-Language: cs
            X-Previo-App-ID: 3
            Authorization: Bearer 7e8HVcDWhnHnQCL8wqvKM95c7e8HVcDW
            X-Device-UUID: 765ce9ec-29f2-423a-9724-6512cef6bf19
            
    + Attributes (AssaAbloyEndpointId)
            
+ Response 200 (application/json)

+ Response 400 (application/json)
    + Attributes (Error)

+ Response 401 (application/json)
    + Attributes (AuthTimeoutError)

## Hotel [/hotel]

### Get hotel info [GET /hotel]

+ Request (application/json)
    + Headers
    
            Accept-Language: cs
            X-Previo-App-ID: 3
            Authorization: Bearer 7e8HVcDWhnHnQCL8wqvKM95c7e8HVcDW
            X-Device-UUID: 765ce9ec-29f2-423a-9724-6512cef6bf19
            
+ Response 200 (application/json)
    + Attributes (Hotel)
    
+ Response 404 (application/json) 
    + Attributes (Error)

### Get attractions around [GET /hotel/attraction]

+ Request (application/json)
    + Headers
    
            Accept-Language: cs
            X-Previo-App-ID: 3
            Authorization: Bearer 7e8HVcDWhnHnQCL8wqvKM95c7e8HVcDW
            X-Device-UUID: 765ce9ec-29f2-423a-9724-6512cef6bf19
            
+ Response 200 (application/json)
    + Attributes (array[Attraction])

### Get trips [GET /hotel/trip]

+ Request (application/json)
    + Headers
    
            Accept-Language: cs
            X-Previo-App-ID: 3
            Authorization: Bearer 7e8HVcDWhnHnQCL8wqvKM95c7e8HVcDW
            X-Device-UUID: 765ce9ec-29f2-423a-9724-6512cef6bf19
            
+ Response 200 (application/json)
    + Attributes (array[Trip])

## Hotel account [/account]

### Account [GET]

+ Request (application/json)
    + Headers
    
            Accept-Language: cs
            X-Previo-App-ID: 3
            Authorization: Bearer 7e8HVcDWhnHnQCL8wqvKM95c7e8HVcDW
            X-Device-UUID: 765ce9ec-29f2-423a-9724-6512cef6bf19

+ Response 200 (application/json)
    + Attributes (Account)

+ Response 401 (application/json)
    + Attributes (AuthTimeoutError)

## Services [/service]

### Services list [GET /service]

+ Request (application/json)
    + Headers
    
            Accept-Language: cs
            X-Previo-App-ID: 3
            Authorization: Bearer 7e8HVcDWhnHnQCL8wqvKM95c7e8HVcDW
            X-Device-UUID: 765ce9ec-29f2-423a-9724-6512cef6bf19
            
+ Response 200 (application/json)
    + Attributes (array[Service])
    
+ Response 505 (application/json)
    + Attributes (ReservationEndedError)

### Order service [POST /service/order]

+ Request (application/json)
    + Headers
    
            Accept-Language: cs
            X-Previo-App-ID: 3
            Authorization: Bearer 7e8HVcDWhnHnQCL8wqvKM95c7e8HVcDW
            X-Device-UUID: 765ce9ec-29f2-423a-9724-6512cef6bf19

    + Attributes (ServiceOrder)
            
+ Response 200 (application/json)

+ Response 505 (application/json)
    + Attributes (ReservationEndedError)

### Green Option [POST /service/greenOption]

+ Request (application/json)
    + Headers
    
            Accept-Language: cs
            X-Previo-App-ID: 3
            Authorization: Bearer 7e8HVcDWhnHnQCL8wqvKM95c7e8HVcDW
            X-Device-UUID: 765ce9ec-29f2-423a-9724-6512cef6bf19

    + Attributes (GreenOption)

+ Response 400 (application/json)
    + Attributes (Error)

+ Response 401 (application/json)
    + Attributes (AuthTimeoutError)

## System [/system]

### Code books [GET /system/codeBook]

+ Request (application/json)
    + Headers
    
            Accept-Language: cs
            X-Previo-App-ID: 3

+ Response 200 (application/json)
    + Attributes (CodeBook)

## Data Structure

## Error
+ code: 402 (number,required)
+ error: Failed to get data (string,required)
+ message: Nepodařilo se získat data (string,required)

## AuthError
+ code: 400 (number,required)
+ error: Failed to authenticate pin code (string,required)
+ message: Nepodařilo se ověřit pin (string,required)

## AuthRefreshError
+ code: 400 (number,required)
+ error: Failed to refresh access token (string,required)

## AuthTimeoutError
+ code: 401 (number,required)
+ error: Authentication token expired (string,required)
+ message: Vypršela platnost autorizačního tokenu (string,required)

## ReservationEndedError
+ code: 505 (number,required)
+ error: Reservation ended (string,required)
+ message (string, nullable)

## Review
+ isRecommended: true (boolean,required)
+ service: 2 (number, optional) - Services (1 to 5)
+ staff: 5 (number, optional) - Staff (1 to 5)
+ clean: 1 (number, required) - Cleanness (1 to 5)
+ comfort: 2 (number, required) - Comfort (1 to 5)
+ ratio: 4 (number, required) - Price / value ratio (1 to 5)
+ positiveMessage: Yo mama (string,optional)
+ negativeMessage: Yo mama (string,optional)
+ privateMessage: Yo mama (string,optional)

## Authentication
+ accessToken: 7e8HVcDWhnHnQCL8wqvKM95c7e8HVcDW (string,required) - Access token to be used when acessing resources.
+ tokenType: Bearer (string, required) - The type of the token issued - in this case it will allways be Bearer.
+ refreshToken: 6T8pcDWhnHnQCL8wqvKM95c7e8HVcDW (string,required) - The refresh token, which can be used to obtain new access tokens.Re

## Reservation
+ resId: 12060507 (number,required) - The unique identifier for reservation
+ hotId: 3209 (number,required) - The unique identifier for hotel
+ hasReview: false (boolean, required) - true if user already reviewed this reservation
+ commissions (array[Commission], required)
+ contactPerson (ContactPerson, optional)
+ paymentType: 1 (number, required) - Type of payment (0 - Payment in Previo, 1 - Invoice, 2 - OTA)
+ voucher: ABCDDEDS (string, required)
+ note: Bar bar (string, optional)
+ requirePayment: false (boolean, required)

## Commission
+ comId: 123456 (number,required) - The unique identifier for commission
+ cosId: 1 (number,required) - The unique identifier for commission status (ReservationStatus)
+ termFrom: `2017-07-02T06:55:00` (string,required) - ISO 8601
+ termTo: `2017-07-02T06:55:00` (string,required) - ISO 8601
+ greenOption (GreenOption, optional) - Green option commission setting
+ room: Moderní ubytování s příjemnou postelí (string, required) - Name of room
+ roomKind: Dvoulůžkový (string, required) - Name of room kind
+ guests (array[Guest], required)
+ completeCheckin: true (boolean, required) - Commission complete checkin

## Guest
+ gueId: 1233 (number,required) - The unique identifier for guest
+ hasCompleteInfo: false (boolean, required) - If the host has filled in all the data required to check in
+ firstName: Radim (string,optional)
+ lastName: Vaculik (string,optional)
+ email: radim@vaculik.cz (string,optional)
+ phone: +420421123987 (string,optional)
+ guaId: 1 (number, required) - The unique identifier for guest category (GuestCategory)
+ isRecreation: true (boolean,required)
+ birthDate: `2017-01-01T00:00:00` (string,optional) - ISO 8601
+ birthPlace: London (string, optional)
+ identity (Identity, optional) - Identity of guest
+ visa: HD55AIJCS9-4GD-9S (string, optional) - Visa od guest
+ numberPlate: 7A7 5070 (string, optional) - Number plate od guest`s car
+ nationality: 1 (number, optional) - Country id of guest nationality
+ address (AddressGuest, required)

## GreenOption
+ skipCleaningTomorrow: true (boolean, required) - Cleaning will be skipped tomorrow

## GuestCheckIn
+ gueId: 1233 (number,required) - The unique identifier for guest
+ hasCompleteInfo: false (boolean, required) - If the host has filled in all the data required to check in
+ firstName: Radim (string,required)
+ lastName: Vaculik (string,required)
+ email: radim@vaculik.cz (string,optional)
+ phone: +420421123987 (string,optional)
+ isRecreation: true (boolean,required)
+ birthDate: `2017-01-01T00:00:00` (string,required) - ISO 8601
+ birthPlace: London (string, optional)
+ identity (Identity, required) - Identity of guest
+ visa: 21313KDMFS32 (string, optional) - Visa number
+ numberPlate: 5AN6312 (string, optional) - Number plate of guest`s car
+ nationality: 1 (number, required) - Country id of guest nationality
+ address (AddressGuestCheckIn, required)

## GuestCheckInSignature
+ resId: 12060507 (number,required) - The unique identifier for reservation
+ gueId: 1233 (number,required) - The unique identifier for guest
+ signature: iVBORw0KGgoAAAANSUhEU... (string, required) - Base64 encoded signature image

## NoteCheckIn
+ note: some note (string,optional)
+ checkInTime: 18:30 (string,optional)

## Identity
+ number: N5646645 (string, required)
+ guiId: 1 (number, required) - 1 ID card, 2 passport, 3 driving license, 4 permanent residence

## ContactPerson
+ name: Radim Vaculik (string,optional)
+ email: radim@vaculik.cz (string,optional)
+ phone: +420321439439 (string,optional)

## Keychain
+ openDoorByApp: true (boolean, required) - The hotel has locks that support unlocking through alfred
+ state: 10 (number, required) - The key allocation status (1 - not issued, 3 - reservation need to be paid, 4 - can request key , 6 - sent a confirmation email, 10 - keys are ready for use)
+ brand: 3 (number, optional) - Supplier of locking system  (null - not supported open door by app, 1 - Salto, 3 - Assa Abloy, 6 - SmartLock, 8 - AcsLinePin, 9 - SmartLock online, 10 - Custom PIN)
+ keys (array[DoorKey], required) - Array of valid keys

## DoorKey
+ clcId: 321 (number, required) - The unique identifier for key
+ type: 1 (number, required) -  Type of using key (1- bluetooth, 2 - number)
+ name: Room 201 (string, required) - Key name of the door
+ value: laH6wSG0n4xmTZVVWrfKQWVXUwKALHjVMgutn5Cu (string, optional) - Value of key (key hash/pin code). Assa Abloy return null

## Hotel
+ hotId: 3209 (number,required) - The unique identifier for hotel
+ name: Hotel Janacek (string,required)
+ channelHash: 15xzry0E%&sNyanZYwqE (string, required) - Hash of Pusher chanel for hotel
+ address (Address,required)
+ wirelessNetworks (array[WirelessNetwork], required) - Array of wireless networks
+ url: http://www.hoteljanacek.cz (string,optional)
+ phone: +420251613924 (string,optional)
+ arrival: 15:00:00 (string,required)
+ departure: 10:00:00 (string,required)
+ greenOption (GreenOptionGet, required) - Is hotel supporting housekeeping Green Option
+ accommodation (Accommodation, required)
+ restaurants (array[Restaurant], required)
+ wellness (array[Wellness], required)
+ sportsGrounds (array[SportsGround], required)
+ conferenceRooms (array[ConferenceRoom], required)
+ primaryColor: #59b553 (string,required)
+ logo (Logo, required) - Hotel logo
+ cancellationPolicies (array[CancelationPolicy], required) - Cancellation policy for reservation in hotel
+ enablePayment: true (boolean, required) - Support hotel payment in My Alfred app
+ alfredActive: true (boolean, required) - Hotel has active full version of My Alfred app
+ requiredVisaCouIds: 33, 48, 342 (array, required) -  Visa for hotel
+ privacySetting (array[PrivacySetting], required) - Processing of personal data setting
+ alfredSetting (array[AlfredSetting], required)

## GreenOptionGet
+ isSupported: true (boolean, required) - Is hotel supporting housekeeping Green Option
+ showNotificationAtTime: 20000 (number) - number of seconds since the start of the day, when the notification should be sent

## WirelessNetwork
+ ssid: WiFi - My Alfred (string, required) - Name of wireless network
+ password: null (string, optional) - Password of wireless network, if null wireless network is open

## CancelationPolicy
+ period: 48 (number, required) - How many hours before reservation cancellation is this condition valid
+ ammount: 2 (number, required) - The amount of the fee in selected unit
+ unit: 1 (number, required) - The unit of the cancellation fee

## AlfredSetting
+ allowCheckIn: true (boolean, required) - Is allow check-in in Alfred?
+ allowSignature: true (boolean, required) - Guest can sign the check-in
+ allowOnlinePayment: true (boolean, required) - Is allow online payment in Alfred?
+ keyBoxNumber: 722456789 (string, optional) - Phone number for GSM Key Box
+ emergencyCall: 722456789 (string, optional) - Phone number for emergency call

## PrivacySetting
+ policyType: 1 (number, required) - The unique identifier for type of processing of personal data 0 - turn off
+ policyText: Something about processing of personal data (string, optional)

## AddressGuestCheckIn
+ street: Panska 6 (string, required)
+ streetNumber: 6 (string, required)
+ city: Brno (string, required)
+ zip: 60200 (string, required)
+ couId: 1 (number, required) - The unique identifier for country
+ streetType: utca (string, optional) - Type of street for Hungary hotel

## AddressGuest
+ street: Panska 6 (string, optional)
+ streetNumber: 6 (string, optional)
+ city: Brno (string,optional)
+ zip: 60200 (string,optional)
+ couId: 1 (number,required) - The unique identifier for country
+ streetType: utca (string, optional) - Type of street for Hungary hotel

## Address
+ street: Panska (string, required)
+ streetNumber: 6 (string, optional)
+ city: Brno (string, required)
+ zip: 60200 (string, required)
+ couId: 1 (number, required) - The unique identifier for country
+ gps: 50°09'37.1"N 14°23'54.0"E (string, optional)

## Accommodation
+ title: Accommodation hotel Brno (string, required)
+ shortDescription: Bla bla Accommodation (string, required)
+ longDescription: Meh meh Accommodation (string, optional)
+ photos (array[Photo], required) - Photo of hotel accommodation

## Restaurant
+ obkId: 2564 (number, required) - The unique identifier for object kind
+ name: Coyote Diners & Bar (string, required)
+ description: `Restaurace zabývající se čistě americkou kuchyní za pomocí jednoduchosti přípravy a kvality surovin. Těšit se můžete na pokrmy z grilu, originální domácí moučníky či na klasické burgery. Nabídka koktejlů, rozvoz jídla. TV, Wi-Fi, možný vstup se psy, letní zahrádka, parkoviště.` (string, optional)
+ openingHours (OpeningHour, optional)
+ photos (array[Photo], required) - Array of resturant photos

## Wellness
+ obkId: 2564 (number, required) - The unique identifier for object kind
+ name: Pytloun Wellness (string, required)
+ description: `Pytloun Wellness *** Liberec se nachází v klidné lokalitě, přesto v blízkosti centra města Liberec. Nedaleko hotelu můžete navštívit turisticky atraktivní místa, mezi která patří i zábavní centrum Babylon s aquaparkem, IQparkem a lunaparkem. V zimě zdejší ubytování ocení zejména milovníci lyžování. Pouhé tři kilometry od hotelu je Skiareál Ještěd, který uspokojí i náročné lyžaře. Hotel disponuje hezkými pokoji i apartmány. Všichni hosté zde mohou využívat kuchyňku. Samozřejmostí je bezdrátové připojení k internetu v celém objektu.` (string, optional)
+ openingHours (OpeningHour, optional)
+ photos (array[Photo], required) - Array of wellness photos

## SportsGround
+ obkId: 2564 (number, required) - The unique identifier for object kind
+ name: Badminton (string, required)
+ description: `Badminton je individuální olympijský raketový sport. Jeho přímým předchůdcem je indická poona. Při hře dva protivníci (nebo dvě dvojice) odpalují přes síť pomocí rakety míček (košík) a snaží se donutit protivníka k chybě.` (string, optional)
+ openingHours (OpeningHour, optional)
+ photos (array[Photo], required) - Array of sportsGround photos

## ConferenceRoom
+ obkId: 2564 (number, required) - The unique identifier for object kind
+ name: Badminton (string, required)
+ description: `Balkónem s výhledem do zahrady vyniká první konferenční místnost čtyřhvězdičkového Hotelu U Tří korunek v Praze. Místnost díky své rozloze 70m2 nabízí variabilní uspořádání přesně podle požadavků zákazníka.` (string, optional)
+ openingHours (OpeningHour, optional)
+ photos (array[Photo], required) - Array of conference room photos

## OpeningHour
+ mon (array[OpeningHourInterval], required) - Monday (Closed if array empty)
+ tue (array[OpeningHourInterval], required) - Tuesday (Closed if array empty)
+ wed (array[OpeningHourInterval], required) - Wednesday (Closed if array empty)
+ thu (array[OpeningHourInterval], required) - Thursday (Closed if array empty)
+ fri (array[OpeningHourInterval], required) - Friday (Closed if array empty)
+ sat (array[OpeningHourInterval], required) - Saturday (Closed if array empty)
+ sun (array[OpeningHourInterval], required) - Sunday (Closed if array empty)

## OpeningHourInterval
+ from: `08:00` (string, required)
+ to: `22:00` (string, required)

## Account
+ resId: 1235 (number,required) - The unique identifier for reservation (Reservation)
+ groupAccount (GroupAccount)
+ roomAccounts (array[RoomAccount], required)

## GroupAccount
+ total: 100.00 (number,required)
+ paid: 50.00 (number, required) 
+ curId: 1 (number, required) - The unique identifier for currency
+ items (array[AccountItem], required)

## RoomAccount
+ comId: 12345 (number,required) - The unique identifier for commission (Commission)
+ total: 100.00 (number,required)
+ paid: 50.50 (number, required) 
+ curId: 1 (number, required) - The unique identifier for currency
+ items (array[AccountItem], required)

## AccountItem
+ coaId: 342 (number, required) - The unique identifier for account item
+ name: Fried Onion Burger (string, required)
+ price: 100.50 (number, required) - Price of one item
+ count: 1 (number, required) - Count of items

## Attraction
+ attId: 322 (number, required) - The unique identifier for attraction
+ attractionTypes: 1, 2 (array[number], required)
+ isRecommended: true (boolean, required) - Show place in slider
+ name: SpaceX Launch and Landing Control Center (string, required) 
+ description: The SpaceX bid was for exclusive use of the launch complex to ... and control systems with substantial new plumbing for a variety of (string, required)
+ photo (Photo, optional)
+ address (AddressAttraction, required)
+ distance: 5.84 (number, optional) - The linear distance from attraction to hotel. (only if attraction has GPS provided) Unit: km

## AddressAttraction
+ street: Panska (string, optional)
+ streetNumber: 6 (string, optional)
+ city: Brno (string, optional)
+ zip: 60200 (string, optional)
+ couId: 1 (number, required) - The unique identifier for country
+ gps: 50°09'37.1"N 14°23'54.0"E (string, optional)

## Trip
+ httId: 3943 (number, required) -  The unique identifier for trip or tip
+ name: Trip to the lookout tower (string, required) - Name of trip
+ description: Directly above the village, like a wall from formidable sandstone rocks, Vranovský hřeben is raising Vranov ridge. On its top on the rocky ledge above the Jizera is the view point and the ruins of castle Vranov, which was rebuilt in the spirit of Romanticism as the Pantheon. (string, required) - Description of the trip
+ photos (array[Photo], required) - Array of trip photos
+ address (GPS, optional)
+ distance: 2.1 (number, optional) - The distance of the trip. Unit: km
+ externalUrl: https://mapy.cz/s/lafomegura (string, optional) - Link to any URL - restaurant menu, trip directions etc.

## GPS
+ gps: 50°09'37.1"N 14°23'54.0"E (string, optional)

## Service 
+ pckId: 31 (number, required) -  The unique identifier for service
+ pcuId: 1 (number, required) - The unique identifier for service unit
+ isCheckbox: true (boolean, required) - Service is ordered by number or by checkbox
+ name: Breakfast in bed (string, required) - Title of service
+ description: The SpaceX bid was for exclusive use of the launch complex to ... and control systems with substantial new plumbing for a variety of (string, optional)
+ price: 345.23 (number, required) - Price of service
+ curId: 1 (number, required) - The unique identifier for currency
+ photo (Photo, optional)

## ServiceOrder
+ pckId: 31 (number, required) -  The unique identifier for service
+ quantity: 1 (number, required) - Amount of purchased services
+ preferredDatetime: `2018-01-14T13:45:00` (string, optional) - Prefered datetime in ISO 8601
+ note: Note guest on the order (string, optional) - Guest`s not on the order

## GuestCategory
+ guaId: 1 (number, required)
+ name: `Dítě do 6-ti let` (string, required)
+ ageFrom: 0 (number, required)
+ ageTo: 6 (number, required)

## PayUrl
+ url: https://booking.previo.cz/gate/request/51a8d26a289179e6aa193c0564fa525b/ (string, required) - Pay url for pay reservation or one commission

## CodeBook
+ commissionStatuses (array[CommisionStatus], required) - Array of commission status
+ attractionTypes (array[AttractionType], required) - Array of type of attractions
+ currencies (array[Currency], required) -  Array of currency
+ countries (array[Country], required) - Array of country
+ genders (array[Gender], required) - Array of gender
+ identityTypes (array[IdentityType], required) - Array of identity types
+ unit (Unit, required) - Custom Previo units
+ streetTypes (array[StreetTypes], required) - Array of Hungary street type

## CommisionStatus
+ cosId: 1 (number,required) - The unique identifier for commision status
+ name: Option (string, required) - Name of commission status

## AttractionType
+ atyId: 1 (number, required) - The unique identifier for attraction type
+ name: Nature (string, required) - Name of attraction type

## Currency
+ curId: 1 (number, required) - The unique identifier for currency
+ code: EUR (string, required) - Code of currency (ISO 4217)
+ symbol: € (string, required) - Symbol of currency
+ position: left (string, required) - Position of currency symbol

## Country
+ couId: 1 (number, required) - The unique identifier for country
+ name: Czech Republic (string, required) - Name of country
+ code: CZ (string, required) - Code of country
+ flag: https://admin.previo.cz/share/image/country/cz.svg (string, required) - URL to country flag
+ top: true (boolean, required) - Is country top

## Gender
+ genId: 1 (number, required) - The unique identifier for gender
+ name: Male (string, required) - Name of gender

## IdentityType
+ guiId: 1 (number, required) - The unique identifier for guest identity type
+ name: Identity card (string, required) - Name of guest identity type

## StreetTypes
+ id: 1 (number, required) - The unique identifier for street type
+ name: utca (string, required) - Name of street type

## Unit
+ services (array[ServiceUnit], required) - Array of service units (per room, per person, per item, per night, per person/nigt, per room/night)

## ServiceUnit
+ pcuId: 1 (number, required) - The unique identifier for service unit
+ text: /per. (string, required) - Text representation of unit
+ description: Price is per each person. (string, required) - Description of service unit

## Logo
+ url: `https://ihg.scene7.com/is/image/ihg/HI_logo_LVP_@2x` (string, required)
+ height: 95 (number, required) - In pixel
+ width: 335 (number, required) - In pixel

## Photo
+ url: `https://www.demilked.com/magazine/wp-content/uploads/2014/12/norway-landscape-photography-scandinavian-nature-4.jpg` (string, required)
+ height: 720 (number, required) - In pixel
+ width: 960 (number, required) - In pixel

## AssaAbloyEmail
+ email: user@example.com (string, required) - New mail for confirmation mail

## AssaAbloyEndpointId
+ endpoint: `7dc53df5-703e-6en32-8670-b1c468f7sk2df` (string, required) - Name of device endpoint in Assa Abloy