FORMAT: 1A
HOST: https://api.previo.cz/app/

# API - Alfred app

## Notification - OneSignal
 - On login
   - `resId = 123456`
   - `active = true`
 - On logout
   - `active = false`

### Type
  - Online check-in: opens check-in screen
    - `type = notification`
    - `title = ...`
    - `message = ...`
    - `screen = check-in`
  - New/Remove account item: opens account
    - `type = notification`
    - `title = ...`
    - `message = ...`
    - `screen = account`
    - `action = refresh`
  - Pay: Opens pop-up screen with pay
    - `type = notification`
    - `title = ...`
    - `message = ...`
    - `screen = pay`
    - `action = refresh`
  - Review: Open review screen
    - `type = notification`
    - `title = Ohodnoťte Váš pobyt`
    - `message = Protože nám záleží na vašem názoru`
    - `screen = review`
  - Internal:
    - `type = internal`
    - `action = refresh`
 
### Parameters
- `type` - internal|notification
- `action` - none|refresh
- `screen` - review|pay|account|check-in|main
- `title` - string
- `message`

## Deep Links
- `alfred://payment/success` - opens success dialog
- `alfred://payment/fail` - opens fail dialog

## Authentication [/authentication]

### Get access token [GET /authentication/accessToken{?code}]

`In development`

+ Request (application/json)
    + Headers

            Accept-Language: cs
            X-Previo-App-ID: 3
            User-Agent: iPhoneX - Model name of user device
            
+ Parameters
    + code: ABC123 (string,required) - Unique reservation or commission identifier, 6 capital chars and numbers
    
+ Response 200 (application/json)
    + Attributes (Authentication)
    
+ Response 400 (application/json) 
    + Attributes (AuthError)

### Refresh access token [GET /authentication/refreshToken{?refreshToken}]

`In development`

+ Request (application/json)
    + Headers

            Accept-Language: cs
            X-Previo-App-ID: 3

+ Parameters
    + refreshToken: 7e8HVcDWhnHnQCL8wqvKM95c7e8HVcDW (string,required) - The refresh token.
    
+ Response 200 (application/json)
    
+ Response 400 (application/json) 
    + Attributes (AuthRefreshError)

## Reservation [/reservation]

### Get reservation [GET /reservation]

`In development`

+ Request (application/json)
    + Headers
    
            Accept-Language: cs
            X-Previo-App-ID: 3
            Authorization: Bearer 7e8HVcDWhnHnQCL8wqvKM95c7e8HVcDW
            
+ Response 200 (application/json)
    + Attributes (Reservation)
    
+ Response 404 (application/json) 
    + Attributes (Error)
    
+ Response 401 (application/json)
    + Attributes (AuthTimeoutError)

### Cancel reservation [PUT /reservation/cancel]

`In development`

+ Request (application/json)
    + Headers
    
            Accept-Language: cs
            X-Previo-App-ID: 3
            Authorization: Bearer 7e8HVcDWhnHnQCL8wqvKM95c7e8HVcDW
    
+ Response 200 (application/json)

+ Response 400 (application/json)
    + Attributes (Error)

### Check in [PUT /reservation/checkIn]

`In development`

+ Request (application/json)
    + Attributes (GuestCheckIn)
    + Headers
    
            Accept-Language: cs
            X-Previo-App-ID: 3
            Authorization: Bearer 7e8HVcDWhnHnQCL8wqvKM95c7e8HVcDW
        
+ Response 200 (application/json)

+ Response 400 (application/json)
    + Attributes (Error)

### Check out [PUT /reservation/checkOut]

`In development`

+ Request (application/json)
    + Headers
    
            Accept-Language: cs
            X-Previo-App-ID: 3
            Authorization: Bearer 7e8HVcDWhnHnQCL8wqvKM95c7e8HVcDW

+ Response 200 (application/json)

+ Response 400 (application/json)
    + Attributes (Error)
    
+ Response 401 (application/json)
    + Attributes (AuthTimeoutError)

### Pay [POST /reservation/pay{?comId}{?groupAccount}]

`In development - not implement in app`

+ Request (application/json)
    + Headers
    
            Accept-Language: cs
            X-Previo-App-ID: 3
            Authorization: Bearer 7e8HVcDWhnHnQCL8wqvKM95c7e8HVcDW

+ Parameters
    + comId: 93481 (number, optional) - Unique commission identifier, if we want to pay one room account only
    + groupAccount: true (boolean, optional) - Pay group account only if true

+ Response 200 (application/json)
    + Attributes (PayUrl)
    
+ Response 400 (application/json)
    + Attributes (Error)
    
+ Response 401 (application/json)
    + Attributes (AuthTimeoutError)

### Post review [POST /reservation/review]

`In development`

+ Request (application/json)
    + Attributes (Review)
    + Headers
    
            Accept-Language: cs
            X-Previo-App-ID: 3
            Authorization: Bearer 7e8HVcDWhnHnQCL8wqvKM95c7e8HVcDW
            
+ Response 200 (application/json)

+ Response 400 (application/json)
    + Attributes (Error)

+ Response 401 (application/json)
    + Attributes (AuthTimeoutError)
    
## Hotel [/hotel]

### Get hotel info [GET /hotel]

`In development`

+ Request (application/json)
    + Headers
    
            Accept-Language: cs
            X-Previo-App-ID: 3
            Authorization: Bearer 7e8HVcDWhnHnQCL8wqvKM95c7e8HVcDW
            
+ Response 200 (application/json)
    + Attributes (Hotel)
    
+ Response 404 (application/json) 
    + Attributes (Error)

### Get attractions around [GET /hotel/attraction]

`In development`

+ Request (application/json)
    + Headers
    
            Accept-Language: cs
            X-Previo-App-ID: 3
            Authorization: Bearer 7e8HVcDWhnHnQCL8wqvKM95c7e8HVcDW
            
+ Response 200 (application/json)
    + Attributes (array[Attraction])

## Hotel account [/account]

### Account [GET]

`In development`

+ Request (application/json)
    + Headers
    
            Accept-Language: cs
            X-Previo-App-ID: 3
            Authorization: Bearer 7e8HVcDWhnHnQCL8wqvKM95c7e8HVcDW

+ Response 200 (application/json)
    + Attributes (Account)

+ Response 401 (application/json)
    + Attributes (AuthTimeoutError)

## Services [/service]

### Services list [GET /service]

`In development`

+ Request (application/json)
    + Headers
    
            Accept-Language: cs
            X-Previo-App-ID: 3
            Authorization: Bearer 7e8HVcDWhnHnQCL8wqvKM95c7e8HVcDW
            
+ Response 200 (application/json)
    + Attributes (array[Service])
    
+ Response 505 (application/json)
    + Attributes (ReservationEndedError)

### Order service [POST /service/order]

`In development`

+ Request (application/json)
    + Headers
    
            Accept-Language: cs
            X-Previo-App-ID: 3
            Authorization: Bearer 7e8HVcDWhnHnQCL8wqvKM95c7e8HVcDW

    + Attributes (ServiceOrder)
            
+ Response 200 (application/json)

+ Response 505 (application/json)
    + Attributes (ReservationEndedError)

## System [/system]

### Code books [GET /system/codeBook]

`In development`

+ Request (application/json)
    + Headers
    
            Accept-Language: cs
            X-Previo-App-ID: 3

+ Response 200 (application/json)
    + Attributes (CodeBook)

## Data Structure

## Error
+ code: 402 (number,required)
+ error: Failed to get data (string,required)
+ message: Nepodařilo se získat data (string,required)

## AuthError
+ code: 400 (number,required)
+ error: Failed to authenticate pin code (string,required)
+ message: Nepodařilo se ověřit pin (string,required)

## AuthRefreshError
+ code: 400 (number,required)
+ error: Failed to refresh access token (string,required)

## AuthTimeoutError
+ code: 401 (number,required)
+ error: Authentication token expired (string,required)
+ message: Vypršela platnost autorizačního tokenu (string,required)

## ReservationEndedError
+ code: 505 (number,required)
+ error: Reservation ended (string,required)
+ message (string, nullable)

## Review
+ isRecommended: true (boolean,required)
+ service: 2 (number, optional) - Services (1 to 5)
+ staff: 5 (number, optional) - Staff (1 to 5)
+ clean: 1 (number, required) - Cleanness (1 to 5)
+ comfort: 2 (number, required) - Comfort (1 to 5)
+ ratio: 4 (number, required) - Price / value ratio (1 to 5)
+ positiveMessage: Yo mama (string,optional)
+ negativeMessage: Yo mama (string,optional)
+ privateMessage: Yo mama (string,optional)

## Authentication
+ accessToken: 7e8HVcDWhnHnQCL8wqvKM95c7e8HVcDW (string,required) - Access token to be used when acessing resources.
+ tokenType: Bearer (string, required) - The type of the token issued - in this case it will allways be Bearer.
+ refreshToken: 6T8pcDWhnHnQCL8wqvKM95c7e8HVcDW (string,required) - The refresh token, which can be used to obtain new access tokens.Re

## Reservation
+ resId: 1235 (number,required) - The unique identifier for reservation
+ hotId: 3209 (number,required) - The unique identifier for hotel
+ hasReview: false (boolean, required) - true if user already reviewed this reservation
+ commissions (array[Commission], required)
+ contactPerson (ContactPerson, optional)
+ voucher: ABCDDEDS (string, required)
+ note: Bar bar (string, optional)

## Commission
+ comId: 123456 (number,required) - The unique identifier for commission
+ cosId: 1 (number,required) - The unique identifier for commission status (ReservationStatus)
+ termFrom: `2017-07-02T06:55:00` (string,required) - ISO 8601
+ termTo: `2017-07-02T06:55:00` (string,required) - ISO 8601
+ isCheckIn: false (boolean, required) - If all guests check-in
+ isCheckOut: false (boolean, required) - If all guests check-out
+ room: Moderní ubytování s příjemnou postelí (string, required) - Name of room
+ roomKind: Dvoulůžkový (string, required) - Name of room kind
+ guests (array[Guest], required)

## Guest
+ gueId: 1233 (number,required) - The unique identifier for guest
+ firstName: Radim (string,optional)
+ lastName: Vaculik (string,optional)
+ email: radim@vaculik.cz (string,optional)
+ phone: +420421123987 (string,optional)
+ guaId: 1 (number, required) - The unique identifier for guest category (GuestCategory)
+ isRecreation: true (boolean,required)
+ birthDate: `2017-01-01T00:00:00` (string,optional) - ISO 8601
+ birthPlace: London (string, optional)
+ genId: 1 (number, optional) - The unique identifier for gender (1 man 2 woman)
+ identity (Identity, optional) - Identity of guest
+ visa: HD55AIJCS9-4GD-9S (string, optional) - Visa od guest
+ numberPlate: 7A7 5070 (string, optional) - Number plate od guest`s car
+ nationality: 1 (number, required) - Country id of guest nationality
+ address (AddressGuest, required)

## GuestCheckIn
+ gueId: 1233 (number,required) - The unique identifier for guest
+ firstName: Radim (string,required)
+ lastName: Vaculik (string,required)
+ email: radim@vaculik.cz (string,required)
+ phone: +420421123987 (string,required)
+ guaId: 1 (number, required) - The unique identifier for guest category (GuestCategory)
+ isRecreation: true (boolean,required)
+ birthDate: `2017-01-01T00:00:00` (string,required) - ISO 8601
+ birthPlace: London (string, required)
+ genId: 1 (number, required) - The unique identifier for gender (1 man 2 woman)
+ identity (Identity, required) - Identity of guest
+ nationality: 1 (number, required) - Country id of guest nationality
+ address (AddressGuestCheckIn, required)

## Identity
+ number: N5646645 (string,optional)
+ guiId: 1 (number,optional) - 1 ID card, 2 passport, 3 driving license, 4 permanent residence

## ContactPerson
+ name: Radim Vaculik (string,optional)
+ email: radim@vaculik.cz (string,optional)
+ phone: +420321439439 (string,optional)

## Hotel
+ hotId: 3209 (number,required) - The unique identifier for hotel
+ name: Hotel Janacek (string,required)
+ address (Address,required)
+ url: http://www.hoteljanacek.cz (string,optional)
+ phone: +420251613924 (string,optional)
+ email: info@previo.cz (string,required)
+ arrival: 15:00:00 (string,required)
+ departure: 10:00:00 (string,required)
+ shortDescription: In as name to here them deny wise this. As rapid woody my he me which. Men but they fail shew just wish next put. Led all visitor musical calling nor her.  (string, required)
+ longDescription: In as name to here them deny wise this. As rapid woody my he me which. Men but they fail shew just wish next put. Led all visitor musical calling nor her. Within coming figure sex things are. Pretended concluded did repulsive education smallness yet yet described. Had country man his pressed shewing. No gate dare rose he. Eyes year if miss he as upon.  (string, optional)
+ accommodation (Accommodation, required)
+ restaurants (array[Restaurant], required)
+ wellness (array[Wellness], required)
+ sportsGrounds (array[SportsGround], required)
+ conferenceRooms (array[ConferenceRoom], required)
+ primaryColor: #59b553 (string,required)
+ logo (Logo, required) - Hotel logo
+ photos (array[Photo], required) - Photos of hotel from main gallery in Previo
+ cancellationPolicies (array[CancelationPolicy], required) - Cancellation policy for reservation in hotel

## CancelationPolicy
+ period: 48 (number, required) - How many hours before reservation cancellation is this condition valid
+ ammount: 2 (number, required) - The amount of the fee in selected unit
+ unit: 1 (number, required) - The unit of the cancellation fee

## AddressGuestCheckIn
+ street: Panska 6 (string, required)
+ streetNumber: 6 (string, required)
+ city: Brno (string, required)
+ zip: 60200 (string, required)
+ couId: 1 (number, required) - The unique identifier for country

## AddressGuest
+ street: Panska 6 (string, optional)
+ streetNumber: 6 (string, optional)
+ city: Brno (string,optional)
+ zip: 60200 (string,optional)
+ couId: 1 (number,required) - The unique identifier for country

## Address
+ street: Panska (string, required)
+ streetNumber: 6 (string, optional)
+ city: Brno (string, required)
+ zip: 60200 (string, required)
+ couId: 1 (number, required) - The unique identifier for country
+ lat: 49.01235 (number, optional)
+ lon: 16.56454 (number, optional)

## Accommodation
+ title: Accommodation hotel Brno (string, required)
+ shortDescription: Bla bla Accommodation (string, required)
+ longDescription: Meh meh Accommodation (string, optional)
+ photos (array[Photo], required) - Photo of hotel accommodation

## Restaurant
+ name: Coyote Diners & Bar (string, required)
+ description: `Restaurace zabývající se čistě americkou kuchyní za pomocí jednoduchosti přípravy a kvality surovin. Těšit se můžete na pokrmy z grilu, originální domácí moučníky či na klasické burgery. Nabídka koktejlů, rozvoz jídla. TV, Wi-Fi, možný vstup se psy, letní zahrádka, parkoviště.` (string, optional)
+ openingHours (OpeningHour, optional)
+ photos (array[Photo], required) - Array of resturant photos

## Wellness
+ name: Pytloun Wellness (string, required)
+ description: `Pytloun Wellness *** Liberec se nachází v klidné lokalitě, přesto v blízkosti centra města Liberec. Nedaleko hotelu můžete navštívit turisticky atraktivní místa, mezi která patří i zábavní centrum Babylon s aquaparkem, IQparkem a lunaparkem. V zimě zdejší ubytování ocení zejména milovníci lyžování. Pouhé tři kilometry od hotelu je Skiareál Ještěd, který uspokojí i náročné lyžaře. Hotel disponuje hezkými pokoji i apartmány. Všichni hosté zde mohou využívat kuchyňku. Samozřejmostí je bezdrátové připojení k internetu v celém objektu.` (string, optional)
+ openingHours (OpeningHour, optional)
+ photos (array[Photo], required) - Array of wellness photos

## SportsGround
+ name: Badminton (string, required)
+ description: `Badminton je individuální olympijský raketový sport. Jeho přímým předchůdcem je indická poona. Při hře dva protivníci (nebo dvě dvojice) odpalují přes síť pomocí rakety míček (košík) a snaží se donutit protivníka k chybě.` (string, optional)
+ openingHours (OpeningHour, optional)
+ photos (array[Photo], required) - Array of sportsGround photos

## ConferenceRoom
+ name: Badminton (string, required)
+ description: `Balkónem s výhledem do zahrady vyniká první konferenční místnost čtyřhvězdičkového Hotelu U Tří korunek v Praze. Místnost díky své rozloze 70m2 nabízí variabilní uspořádání přesně podle požadavků zákazníka.` (string, optional)
+ openingHours (OpeningHour, optional)
+ photos (array[Photo], required) - Array of conference room photos

## OpeningHour
+ mon (array[OpeningHourInterval], required) - Monday (Closed if array empty)
+ tue (array[OpeningHourInterval], required) - Tuesday (Closed if array empty)
+ wed (array[OpeningHourInterval], required) - Wednesday (Closed if array empty)
+ thu (array[OpeningHourInterval], required) - Thursday (Closed if array empty)
+ fri (array[OpeningHourInterval], required) - Friday (Closed if array empty)
+ sat (array[OpeningHourInterval], required) - Saturday (Closed if array empty)
+ sun (array[OpeningHourInterval], required) - Sunday (Closed if array empty)

## OpeningHourInterval
+ from: `08:00` (string, required)
+ to: `22:00` (string, required)

## Account
+ resId: 1235 (number,required) - The unique identifier for reservation (Reservation)
+ groupAccount (GroupAccount)
+ roomAccounts (array[RoomAccount], required)

## GroupAccount
+ total: 100.00 (number,required)
+ paid: 50.00 (number, required) 
+ curId: 1 (number, required) - The unique identifier for currency
+ items (array[AccountItem], required)

## RoomAccount
+ comId: 12345 (number,required) - The unique identifier for commission (Commission)
+ total: 100.00 (number,required)
+ paid: 50.50 (number, required) 
+ curId: 1 (number, required) - The unique identifier for currency
+ items (array[AccountItem], required)

## AccountItem
+ coaId: 342 (number, required) - The unique identifier for account item
+ name: Fried Onion Burger (string, required)
+ price: 100.50 (number, required) - Price of one item
+ count: 1 (number, required) - Count of items

## Attraction
+ attId: 322 (number, required) - The unique identifier for attraction
+ attractionTypes: 1, 2 (array[number], required)
+ isRecommended: true (boolean, required) - Show place in slider
+ name: SpaceX Launch and Landing Control Center (string, required) 
+ description: The SpaceX bid was for exclusive use of the launch complex to ... and control systems with substantial new plumbing for a variety of (string, required)
+ photo (Photo, optional)
+ address (AddressAttraction, required)
+ distance: 2.1 (number, optional) - The linear distance from attraction to hotel. (only if attraction has GPS provided) Unit: km

## AddressAttraction
+ street: Panska (string, optional)
+ streetNumber: 6 (string, optional)
+ city: Brno (string, optional)
+ zip: 60200 (string, optional)
+ couId: 1 (number, required) - The unique identifier for country
+ lat: 49.01235 (number, optional)
+ lon: 16.56454 (number, optional)

## Service 
+ pckId: 31 (number, required) -  The unique identifier for service
+ pcuId: 1 (number, required) - The unique identifier for service unit
+ name: Breakfast in bed (string, required) - Title of service
+ description: The SpaceX bid was for exclusive use of the launch complex to ... and control systems with substantial new plumbing for a variety of (string, optional)
+ price: 345.23 (number, required) - Price of service
+ curId: 1 (number, required) - The unique identifier for currency
+ photo (Photo, optional)

## ServiceOrder
+ pckId: 31 (number, required) -  The unique identifier for service
+ quantity: 1 (number, required) - Amount of purchased services

## GuestCategory
+ guaId: 1 (number, required)
+ name: `Dítě do 6-ti let` (string, required)
+ ageFrom: 0 (number, required)
+ ageTo: 6 (number, required)

## PayUrl
+ url: https://booking.previo.cz/gate/request/51a8d26a289179e6aa193c0564fa525b/ (string, required) - Pay url for pay reservation or one commission

## CodeBook
+ commissionStatuses (array[CommisionStatus], required) - Array of commission status
+ attractionTypes (array[AttractionType], required) - Array of type of attractions
+ currencies (array[Currency], required) -  Array of currency
+ countries (array[Country], required) - Array of country
+ genders (array[Gender], required) - Array of gender
+ identityTypes (array[IdentityType], required) - Array of identity types
+ unit (Unit, required) - Custom Previo units

## CommisionStatus
+ cosId: 1 (number,required) - The unique identifier for commision status
+ name: Option (string, required) - Name of commission status

## AttractionType
+ atyId: 1 (number, required) - The unique identifier for attraction type
+ name: Nature (string, required) - Name of attraction type

## Currency
+ curId: 1 (number, required) - The unique identifier for currency
+ code: EUR (string, required) - Code of currency (ISO 4217)

## Country
+ couId: 1 (number, required) - The unique identifier for country
+ name: Czech Republic (string, required) - Name of country

## Gender
+ genId: 1 (number, required) - The unique identifier for gender
+ name: Male (string, required) - Name of gender

## IdentityType
+ guiId: 1 (number, required) - The unique identifier for guest identity type
+ name: Identity card (string, required) - Name of guest identity type

## Unit
+ services (array[ServiceUnit], required) - Array of service units (per room, per person, per item, per night, per person/nigt, per room/night)

## ServiceUnit
+ pcuId: 1 (number, required) - The unique identifier for service unit
+ text: /per. (string, required) - Text representation of unit
+ description: Price is per each person. (string, required) - Description of service unit

## Logo
+ url: `https://ihg.scene7.com/is/image/ihg/HI_logo_LVP_@2x` (string, required)
+ height: 95 (number, required) - In pixel
+ width: 335 (number, required) - In pixel

## Photo
+ url: `https://www.demilked.com/magazine/wp-content/uploads/2014/12/norway-landscape-photography-scandinavian-nature-4.jpg` (string, required)
+ height: 720 (number, required) - In pixel
+ width: 960 (number, required) - In pixel